package beengine.api.entity;

import lombok.experimental.UtilityClass;

/**
 * This file is directly generated from the entity definitions provided by the client. The entities listed in this file
 * are expected to always have the same IDs.
 *
 * This file is automatically generated; do NOT edit it by hand.
 */
@UtilityClass
public class EntityIdsNormal {
	private final String mc = "minecraft:";

	public final String AGENT					 = mc+"agent";
	public final String AREA_EFFECT_CLOUD		 = mc+"area_effect_cloud";
	public final String ARMOR_STAND			 = mc+"armor_stand";
	public final String ARROW					 = mc+"arrow";
	public final String BALLOON				 = mc+"balloon";
	public final String BAT					 = mc+"bat";
	public final String BEE					 = mc+"bee";
	public final String BLAZE					 = mc+"blaze";
	public final String BOAT					 = mc+"boat";
	public final String CAT					 = mc+"cat";
	public final String CAVE_SPIDER			 = mc+"cave_spider";
	public final String CHEST_MINECART		 = mc+"chest_minecart";
	public final String CHICKEN				 = mc+"chicken";
	public final String COD					 = mc+"cod";
	public final String COMMAND_BLOCK_MINECART = mc+"command_block_minecart";
	public final String COW 					 = mc+"cow";
	public final String CREEPER				 = mc+"creeper";
	public final String DOLPHIN				 = mc+"dolphin";
	public final String DONKEY				 = mc+"donkey";
	public final String DRAGON_FIREBALL		 = mc+"dragon_fireball";
	public final String DROWNED 				 = mc+"drowned";
	public final String EGG 					 = mc+"egg";
	public final String ELDER_GUARDIAN 		 = mc+"elder_guardian";
	public final String ELDER_GUARDIAN_GHOST 	 = mc+"elder_guardian_ghost";
	public final String ENDER_CRYSTAL			 = mc+"ender_crystal";
	public final String ENDER_DRAGON			 = mc+"ender_dragon";
	public final String ENDER_PEARL			 = mc+"ender_pearl";
	public final String ENDERMAN				 = mc+"enderman";
	public final String ENDERMITE				 = mc+"endermite";
	public final String EVOCATION_FANG		 = mc+"evocation_fang";
	public final String EVOCATION_ILLAGER		 = mc+"evocation_illager";
	public final String EYE_OF_ENDER_SIGNAL	 = mc+"eye_of_ender_signal";
	public final String FALLING_BLOCK			 = mc+"falling_block";
	public final String FIREBALL				 = mc+"fireball";
	public final String FIREWORKS_ROCKET		 = mc+"fireworks_rocket";
	public final String FISHING_HOOK			 = mc+"fishing_hook";
	public final String FOX					 = mc+"fox";
	public final String GHAST					 = mc+"ghast";
	public final String GUARDIAN				 = mc+"guardian";
	public final String HOGLIN				 = mc+"hoglin";
	public final String HOPPER_MINECART		 = mc+"hopper_minecart";
	public final String HORSE					 = mc+"horse";
	public final String HUSK					 = mc+"husk";
	public final String ICE_BOMB				 = mc+"ice_bomb";
	public final String IRON_GOLEM			 = mc+"iron_golem";
	public final String ITEM					 = mc+"item";
	public final String LEASH_KNOT			 = mc+"leash_knot";
	public final String LIGHTNING_BOLT		 = mc+"lightning_bolt";
	public final String LINGERING_POTION		 = mc+"lingering_potion";
	public final String LLAMA					 = mc+"llama";
	public final String LLAMA_SPIT			 = mc+"llama_spit";
	public final String MAGMA_CUBE			 = mc+"magma_cube";
	public final String MINECART				 = mc+"minecart";
	public final String MOOSHROOM				 = mc+"mooshroom";
	public final String MULE					 = mc+"mule";
	public final String NPC					 = mc+"npc";
	public final String OCELOT				 = mc+"ocelot";
	public final String PAINTING				 = mc+"painting";
	public final String PANDA					 = mc+"panda";
	public final String PARROT				 = mc+"parrot";
	public final String PHANTOM				 = mc+"phantom";
	public final String PIG					 = mc+"pig";
	public final String PIGLIN				 = mc+"piglin";
	public final String PILLAGER				 = mc+"pillager";
	public final String PLAYER				 = mc+"player";
	public final String POLAR_BEAR			 = mc+"polar_bear";
	public final String PUFFERFISH			 = mc+"pufferfish";
	public final String RABBIT				 = mc+"rabbit";
	public final String RAVAGER				 = mc+"ravager";
	public final String SALMON				 = mc+"salmon";
	public final String SHEEP					 = mc+"sheep";
	public final String SHULKER				 = mc+"shulker";
	public final String SHULKER_BULLET		 = mc+"shulker_bullet";
	public final String SILVERFISH			 = mc+"silverfish";
	public final String SKELETON				 = mc+"skeleton";
	public final String SKELETON_HORSE		 = mc+"skeleton_horse";
	public final String SLIME					 = mc+"slime";
	public final String SMALL_FIREBALL		 = mc+"small_fireball";
	public final String SNOW_GOLEM			 = mc+"snow_golem";
	public final String SNOWBALL				 = mc+"snowball";
	public final String SPIDER				 = mc+"spider";
	public final String SPLASH_POTION			 = mc+"splash_potion";
	public final String SQUID					 = mc+"squid";
	public final String STRAY					 = mc+"stray";
	public final String STRIDER				 = mc+"strider";
	public final String THROWN_TRIDENT		 = mc+"thrown_trident";
	public final String TNT					 = mc+"tnt";
	public final String TNT_MINECART			 = mc+"tnt_minecart";
	public final String TRIPOD_CAMERA			 = mc+"tripod_camera";
	public final String TROPICALFISH			 = mc+"tropicalfish";
	public final String TURTLE				 = mc+"turtle";
	public final String VEX					 = mc+"vex";
	public final String VILLAGER				 = mc+"villager";
	public final String VILLAGER_V2			 = mc+"villager_v2";
	public final String VINDICATOR			 = mc+"vindicator";
	public final String WANDERING_TRADER		 = mc+"wandering_trader";
	public final String WITCH					 = mc+"witch";
	public final String WITHER				 = mc+"wither";
	public final String WITHER_SKELETON		 = mc+"wither_skeleton";
	public final String WITHER_SKULL			 = mc+"wither_skull";
	public final String WITHER_SKULL_DANGEROUS = mc+"wither_skull_dangerous";
	public final String WOLF					 = mc+"wolf";
	public final String XP_BOTTLE				 = mc+"xp_bottle";
	public final String XP_ORB				 = mc+"xp_orb";
	public final String ZOGLIN				 = mc+"zoglin";
	public final String ZOMBIE				 = mc+"zombie";
	public final String ZOMBIE_HORSE			 = mc+"zombie_horse";
	public final String ZOMBIE_PIGMAN			 = mc+"zombie_pigman";
	public final String ZOMBIE_VILLAGER		 = mc+"zombie_villager";
	public final String ZOMBIE_VILLAGER_V2	 = mc+"zombie_villager_v2";
}